

POST  http://localhost:8080/login
Content-Type: application/json

{
    "username":"user1",
    "password":"password1"
}


###
GET http://localhost:8080/users?id=asf212333
Authorization: z7c1rdvno39

###
PUT http://localhost:8080/users
Authorization: d62bkwhd154
Content-Type: application/json

{
    "age":50,e
    "email":"some@othermail.com",
    "name":"bbbb",
    "workingPosition":5
}

